// Prints the notes of the current release, published as a single GitHub
// release for all packages: the changes from the changelogs of every package
// for this version, grouped by change type.
//
//   ### New features
//
//   - Added `Kurdistan` flag (#9)
//
//   ### Fixes and improvements
//
//   - **React, Vue:** Fix the `variant` prop type (#12)
//
// An entry shared by several packages is listed once, entries of the main
// package need no label, "Updated dependencies" entries are left out.
import { readFileSync } from 'fs';
import { globSync } from 'glob';
import { dirname, resolve } from 'path';
import { PACKAGES_DIR } from './helpers.mjs';

const MAIN_PACKAGE = '@tabler/flags';

// Changelog sections of Changesets and their headings in the release notes
const CHANGE_TYPES = {
  Major: 'Breaking changes',
  Minor: 'New features',
  Patch: 'Fixes and improvements',
};

const PACKAGE_LABELS = {
  '@tabler/flags-astro': 'Astro',
  '@tabler/flags-png': 'PNG',
  '@tabler/flags-preact': 'Preact',
  '@tabler/flags-react': 'React',
  '@tabler/flags-vue': 'Vue',
};

// "- [#1](url) [`sha`](url) - Summary" generated by
// @changesets/changelog-github, every part before the summary is optional
const ENTRY_REGEX = /^- (?:(?:\[#(\d+)\]\([^)]+\))? ?(?:\[`[0-9a-f]+`\]\([^)]+\))? - )?(.*)$/;

// Changes the entry to "- Summary (#1)"
const formatEntry = (entry) => {
  const [firstLine, ...continuation] = entry.split('\n');
  const [, pull, summary] = firstLine.match(ENTRY_REGEX);

  return [`- ${summary}${pull ? ` (#${pull})` : ''}`, ...continuation].join('\n');
};

const { version } = JSON.parse(readFileSync(resolve(PACKAGES_DIR, 'flags/package.json'), 'utf-8'));
const escapedVersion = version.replace(/\./g, '\\.');

// { [type]: Map<entry, packages[]> } in the order the entries first appear,
// starting with the main package
const changes = Object.fromEntries(Object.keys(CHANGE_TYPES).map((type) => [type, new Map()]));

const packages = globSync(resolve(PACKAGES_DIR, '*/CHANGELOG.md'))
  .map((changelogPath) => ({
    name: JSON.parse(readFileSync(resolve(dirname(changelogPath), 'package.json'), 'utf-8')).name,
    changelog: readFileSync(changelogPath, 'utf-8'),
  }))
  .sort((a, b) => (a.name === MAIN_PACKAGE ? -1 : b.name === MAIN_PACKAGE ? 1 : 0));

packages.forEach(({ name, changelog }) => {
  const [, section = ''] =
    changelog.match(new RegExp(`^## ${escapedVersion}\\n([\\s\\S]*?)(?=^## |(?![\\s\\S]))`, 'm')) ||
    [];

  Object.keys(CHANGE_TYPES).forEach((type) => {
    const [, list = ''] =
      section.match(new RegExp(`^### ${type} Changes\\n([\\s\\S]*?)(?=^### |(?![\\s\\S]))`, 'm')) ||
      [];

    // Top-level list items, together with their indented continuation lines
    list
      .split(/^(?=- )/m)
      .map((entry) => entry.trim())
      .filter((entry) => entry.startsWith('- ') && !entry.startsWith('- Updated dependencies'))
      .map(formatEntry)
      .forEach((entry) => {
        changes[type].set(entry, [...(changes[type].get(entry) || []), name]);
      });
  });
});

Object.entries(CHANGE_TYPES).forEach(([type, heading]) => {
  if (changes[type].size === 0) {
    return;
  }

  console.log(`### ${heading}\n`);

  changes[type].forEach((names, entry) => {
    // Entries of the main package need no label
    const label = names.includes(MAIN_PACKAGE)
      ? ''
      : `**${names
          .map((name) => PACKAGE_LABELS[name] || name)
          .sort()
          .join(', ')}:** `;

    console.log(entry.replace(/^- /, `- ${label}`));
  });

  console.log('');
});
